### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by Timtech4u**
- Updated README file
- Added Code of Conducts & Contributing guides

### CODE REVIEW

**Review by rowanwins — COMMENTED** [review]
Looking good @Timtech4u ! Probably the main question I have is what is the `.yo-rc.json` file for?

**Comment by Timtech4u** [comment]
> Looking good @Timtech4u ! Probably the main question I have is what is the `.yo-rc.json` file for?

Awesome! That was a yeoman generated file, I took it off with my latest commit.

**Review by morganherlocker — APPROVED** [review]
Looks great!

**Comment by Timtech4u** [comment]
> Looks great!

Awesome! Merging this 👍

**Pull request merged**
